OCEANIC_TOP = ..

.PHONY: all test test-local prepare-otp-test info-test-options


# So that it remains the default target:
all:

test: test-local

test-local:


include $(OCEANIC_TOP)/GNUmakesettings.inc
