OCEANIC_TOP = ..

.PHONY: all real-clean


# As shall be the default rule, and as a module must be generated for constants:
all: oceanic_generated.beam


real-clean:
	-@/bin/rm -f oceanic.app.src


include $(OCEANIC_TOP)/GNUmakesettings.inc
