OCEANIC_TOP = ..

.PHONY: all scripts real-clean

# As this module must be generated to share Oceanic constants:
#
# (see the %_generated.beam target in Myriad's GNUmakerules-automatic.inc)
#
EXTRA_BEAM_FILES = oceanic_generated.beam


# As shall be the default rule:
all:


real-clean:
	-@/bin/rm -f oceanic.app.src


include $(OCEANIC_TOP)/GNUmakesettings.inc
